{ pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ./hardware-specific.nix
  ];

  networking.hostName = "strummer";

  # Define the user account
  users.users.philipp = {
    isNormalUser = true;
    description = "Philipp Fleischer";
    extraGroups = [
      "networkmanager"
      "wheel"
    ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB+bSErYniJev/+/UxsilaoxHGYW8oVpd3pYMQuuGStw fleis@Yorke"
    ];
  };

  services.caddy = {
    # virtualHosts are now generated by the service modules!
  };

  # Configure Features
  my.features.services.caddy.baseDomain = "fls.ancoris.ovh";

  my.features.services.home-assistant.expose = {
    enable = true;
    subdomain = "hass";
    auth = false;
  };

  my.features.services.esphome.expose = {
    enable = true;
    auth = true;
  };

  my.features.services.mealie.expose = {
    enable = true;
    auth = false;
  };

  my.features.services.paperless.expose.enable = true;

  my.features.services.prowlarr.expose = {
    enable = true;
    auth = true;
  };

  my.features.services.radarr.expose = {
    enable = true;
    auth = true;
  };

  my.features.services.sabnzbd.expose = {
    enable = true;
    auth = true;
  };

  my.features.services.sonarr.expose = {
    enable = true;
    auth = true;
  };

  my.features.services.jellyfin.expose.enable = true;

  my.features.services.recyclarr.enable = true;

  my.features.services.jellyseerr.expose.enable = true;

  my.features.services.cloudflare-dyndns.domains = [ "ancoris.ovh" ];

  # State version setting
  system.stateVersion = "24.11"; 

}
