#!/usr/bin/env bash
set -e

changed=$(git diff --cached --name-only --diff-filter=ACM | grep '\.nix$' || true)

if [ -n "$changed" ]; then
  echo "==> nixfmt"
  echo "$changed" | xargs -r nixfmt
  echo "$changed" | xargs -r git add
fi

echo "==> deadnix"
echo "$changed" | xargs -r deadnix --fail

echo "==> statix"
if [ -n "$changed" ]; then
  echo "$changed" | xargs -r -n1 statix check
fi
