# .sops.yaml
keys:
  - &philipp age1t2z30qm3c9x7n75nwsra7l97609fkmvz7wjqlsz9ahwsz4a50cwsvjly7j
  - &strummer age15vu7hfhm9ccprhrae3y59gx5dpx7k09ngt6zqynehjrlkhegzpsqk3ltth
  - &mackaye age1t8m78wyupud0akd76rpwsp98m4pha5h70yese52dy0lv2vm7esuq0daq6n

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - pgp: []
        age:
          - *philipp
          - *strummer
          - *mackaye
