#!/usr/bin/env python3
"""VYRX FRITZ!Box Declarative GitOps Sync Engine (TR-064 API).

Reconciles the FRITZ!Box LAN configuration against the declarative specification generated by
Nix: LAN address / subnet mask / addressing type, DHCP server state and range, and WAN port
forwarding. Every managed item is read first and reported as a diff; nothing is written in
--dry-run mode.

Not managed here: the DNS servers the box hands out over DHCP. LANHostConfigManagement:1 has no
setter for them on this device (verified against its own SCPD), and once hom-srv-01 owns DHCP
(Kea) the box stops handing out DNS entirely - so it is a one-time UI setting, reported when it
differs from the desired state.

The LAN address change is destructive by nature: the box moves and the management connection
dies mid-call. It is applied last, its connection error is expected, and the result is verified
against the new address instead.
"""

import argparse
import json
import os
import subprocess
import sys

try:
    from fritzconnection import FritzConnection
except ImportError:
    sys.exit("Error: python library 'fritzconnection' is required.")

LAN = "LANHostConfigManagement1"
WAN = "WANIPConnection1"


def get_password(password_file, secret_path):
    if password_file and os.path.exists(password_file):
        with open(password_file, "r") as f:
            return f.read().strip()
    if "FRITZ_PASSWORD" in os.environ:
        return os.environ["FRITZ_PASSWORD"].strip()
    # Fallback to SOPS decrypt if run in repository root
    if os.path.exists("secrets/secrets.yaml") and secret_path:
        try:
            keys = secret_path.split("/")
            extract_expr = "".join(f'["{k}"]' for k in keys)
            res = subprocess.run(
                ["sops", "-d", "--extract", extract_expr, "secrets/secrets.yaml"],
                capture_output=True,
                text=True,
                check=True,
            )
            return res.stdout.strip()
        except Exception:
            pass
    return None


def read_lan(fc):
    """Current LAN and DHCP state of the box."""
    info = fc.call_action(LAN, "GetInfo")
    rng = fc.call_action(LAN, "GetAddressRange")
    return {
        # This box does not expose the LAN address as its own state variable; it announces
        # itself as the LAN router, which is the same address.
        "address": info.get("NewIPInterfaceIPAddress")
        or info.get("NewIPAddress")
        or info.get("NewIPRouters"),
        "subnet_mask": info.get("NewIPInterfaceSubnetMask") or info.get("NewSubnetMask"),
        "addressing": info.get("NewIPInterfaceIPAddressingType"),
        "dhcp_enabled": info.get("NewDHCPServerEnable"),
        "dhcp_min": rng.get("NewMinAddress"),
        "dhcp_max": rng.get("NewMaxAddress"),
        "dhcp_dns": info.get("NewDNSServers"),
    }


def read_forwards(fc, limit=64):
    """All active WAN port mappings (the IGD service ends the list with an error)."""
    forwards = []
    for index in range(limit):
        try:
            entry = fc.call_action(
                WAN, "GetGenericPortMappingEntry", NewPortMappingIndex=index
            )
        except Exception:
            break
        forwards.append(
            {
                "external_port": entry.get("NewExternalPort"),
                "protocol": entry.get("NewProtocol"),
                "internal_client": entry.get("NewInternalClient"),
                "internal_port": entry.get("NewInternalPort"),
                "description": entry.get("NewPortMappingDescription"),
            }
        )
    return forwards


def show_diff(label, current, desired):
    marker = "=" if current == desired else "~"
    print(f"  [{marker}] {label:<34} current={current!r:<34} desired={desired!r}")


def main():
    parser = argparse.ArgumentParser(
        description="VYRX FRITZ!Box Declarative GitOps Sync Engine"
    )
    parser.add_argument("--spec", required=True, help="Path to desired state JSON file")
    parser.add_argument("--password-file", help="Path to file containing router password")
    parser.add_argument(
        "--dry-run", action="store_true", help="Calculate diff without mutating device state"
    )
    parser.add_argument(
        "action",
        nargs="?",
        default="switch",
        choices=["switch", "dry-run", "test", "status"],
        help="Action to execute (default: switch)",
    )
    args = parser.parse_args()

    if args.action == "dry-run":
        args.dry_run = True

    with open(args.spec, "r") as f:
        spec = json.load(f)

    host = spec["host"]
    user = spec.get("user", "admin")
    settings = spec.get("settings", {})
    lan = settings.get("lan", {})
    dhcp = settings.get("dhcp", {})
    forwards = settings.get("portForwardings", [])

    password = get_password(args.password_file, spec.get("passwordSecret"))
    mode_tag = " [DRY RUN]" if args.dry_run else ""
    print(f"==> Inspecting FRITZ!Box at {host} (TR-064 API){mode_tag}")

    if not password:
        print(f"  [!] No password for {host} - cannot inspect or reconcile. Aborting.")
        sys.exit(1)

    try:
        fc = FritzConnection(address=host, user=user, password=password, timeout=10)
        print(f"  [✓] Connected to: {fc.modelname} (FRITZ!OS {fc.system_version})")
    except Exception as e:
        print(f"  [!] Connection error to {host}: {e}")
        sys.exit(1 if not args.dry_run else 0)

    current = read_lan(fc)
    current_forwards = read_forwards(fc)
    print("  --- diff (current vs desired) ---")
    show_diff("LAN address", current["address"], lan.get("address"))
    show_diff("LAN subnet mask", current["subnet_mask"], lan.get("subnetMask"))
    show_diff("DHCP server", current["dhcp_enabled"], dhcp.get("enable"))
    show_diff("DHCP range from", current["dhcp_min"], lan.get("dhcpRange", {}).get("min"))
    show_diff("DHCP range to", current["dhcp_max"], lan.get("dhcpRange", {}).get("max"))
    if settings.get("dns") is not None:
        print(
            f"  [!] DHCP-announced DNS is {current['dhcp_dns']!r}; the desired "
            f"{settings.get('dns', {}).get('primary')!r} cannot be set over TR-064 "
            "(no such action on this box) - set it in the UI, or stop caring once Kea serves DHCP."
        )
    show_diff("WAN port forwardings", len(current_forwards), len(forwards))
    for f in current_forwards:
        print(
            f"        - {f['protocol']}/{f['external_port']} -> "
            f"{f['internal_client']}:{f['internal_port']} ({f['description']})"
        )
    if forwards:
        print(
            "  [!] A non-empty desired list is not implemented (only 'no forwardings at all',\n"
            "      the Zero-Open-Ports target). Refusing to claim success."
        )
        sys.exit(1)

    if args.dry_run:
        print(f"  [✓] Dry-run complete. No changes applied to {host}.")
        return

    # --- apply (order matters) ------------------------------------------------------------
    # The box validates each argument against its CURRENT LAN subnet: a DHCP range for the new
    # subnet is rejected (error 820) while the box still holds the old address. So the address
    # moves first, and everything subnet-dependent is applied against the new address afterwards.
    changes = 0

    if not forwards and current_forwards:
        for f in current_forwards:
            fc.call_action(
                WAN,
                "DeletePortMapping",
                NewRemoteHost="",
                NewExternalPort=f["external_port"],
                NewProtocol=f["protocol"],
            )
            print(
                f"  [+] removed port forwarding {f['protocol']}/{f['external_port']} "
                f"-> {f['internal_client']}:{f['internal_port']} ({f['description']})"
            )
            changes += 1

    if dhcp.get("enable") != current["dhcp_enabled"]:
        fc.call_action(LAN, "SetDHCPServerEnable", NewDHCPServerEnable=bool(dhcp.get("enable")))
        print(f"  [+] DHCP server {'enabled' if dhcp.get('enable') else 'disabled'}")
        changes += 1

    address_changed = lan.get("address") and lan["address"] != current["address"]
    if address_changed:
        print(
            f"  [*] moving LAN address {current['address']} -> {lan['address']} "
            "(the management connection will drop - this is expected)"
        )
        try:
            fc.call_action(
                LAN,
                "SetIPInterface",
                NewEnable=True,
                NewIPAddress=lan["address"],
                NewSubnetMask=lan.get("subnetMask", current["subnet_mask"]),
                NewIPAddressingType="Static",
            )
        except Exception as e:
            print(f"  [~] connection dropped while moving the box: {e}")
        changes += 1
        # Continue against the new address instead of trusting the dropped connection.
        try:
            fc = FritzConnection(
                address=lan["address"], user=user, password=password, timeout=10
            )
            after = read_lan(fc)
            print(f"  [✓] verified at {lan['address']}: address={after['address']}")
        except Exception as e:
            print(f"  [!] could not reach {lan['address']} yet: {e}")
            print(f"  [✓] Reconciliation stopped after the address change: {changes} change(s).")
            return
    elif lan.get("subnetMask") and lan["subnetMask"] != current["subnet_mask"]:
        fc.call_action(LAN, "SetSubnetMask", NewSubnetMask=lan["subnetMask"])
        print(f"  [+] subnet mask set to {lan['subnetMask']}")
        changes += 1

    # Only now, against the box's new (or unchanged) subnet, is the range a valid argument.
    want_min = lan.get("dhcpRange", {}).get("min")
    want_max = lan.get("dhcpRange", {}).get("max")
    now = read_lan(fc)
    if want_min and want_max and (want_min, want_max) != (now["dhcp_min"], now["dhcp_max"]):
        fc.call_action(LAN, "SetAddressRange", NewMinAddress=want_min, NewMaxAddress=want_max)
        print(f"  [+] DHCP range set to {want_min} - {want_max}")
        changes += 1

    print(f"  [✓] Reconciliation complete for {host}: {changes} change(s).")


if __name__ == "__main__":
    main()
