#!/usr/bin/env python3
"""VYRX Cloudflare Declarative GitOps Sync Engine.

Idempotently reconciles Cloudflare DNS records and Edge TLS settings against a
declarative specification generated by Nix.
"""

import argparse
import json
import os
import subprocess
import sys
import urllib.error
import urllib.request

API_BASE = "https://api.cloudflare.com/client/v4"


def get_token(token_file):
    if token_file and os.path.exists(token_file):
        with open(token_file, "r") as f:
            return f.read().strip()
    if "CLOUDFLARE_API_TOKEN" in os.environ:
        return os.environ["CLOUDFLARE_API_TOKEN"].strip()
    # Fallback to SOPS decrypt if run in repository root
    if os.path.exists("secrets/secrets.yaml"):
        try:
            res = subprocess.run(
                [
                    "sops",
                    "-d",
                    "--extract",
                    '["infra"]["cloudflare_api_token"]',
                    "secrets/secrets.yaml",
                ],
                capture_output=True,
                text=True,
                check=True,
            )
            return res.stdout.strip()
        except Exception:
            pass
    sys.exit(
        "Error: Cloudflare API token not found. Specify --token-file, set"
        " CLOUDFLARE_API_TOKEN, or run in repo with SOPS."
    )


def api_request(token, endpoint, method="GET", data=None):
    url = f"{API_BASE}{endpoint}"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }
    body = json.dumps(data).encode("utf-8") if data else None
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        err_body = e.read().decode("utf-8")
        sys.exit(
            f"Cloudflare API Error [{e.code}] on {method} {endpoint}:"
            f" {err_body}"
        )


def main():
    parser = argparse.ArgumentParser(
        description="VYRX Cloudflare Declarative GitOps Sync Engine"
    )
    parser.add_argument(
        "--spec", required=True, help="Path to desired state JSON file"
    )
    parser.add_argument("--token-file", help="Path to file containing API token")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Calculate diff without mutating state",
    )
    parser.add_argument(
        "--prune",
        action="store_true",
        help="Delete records inside the managed zone that this engine owns and the spec no "
        "longer describes. Records created by anything else (ACME DNS-01, manual entries, "
        "other tooling) are never touched.",
    )
    args = parser.parse_args()

    with open(args.spec, "r") as f:
        spec = json.load(f)

    token = get_token(args.token_file)
    domain = spec["domain"]
    mode_tag = " [DRY RUN]" if args.dry_run else ""
    print(f"==> Reconciling Cloudflare Zone: {domain}{mode_tag}")

    # 1. Fetch Zone ID
    zones = api_request(token, f"/zones?name={domain}")["result"]
    if not zones:
        sys.exit(f"Zone '{domain}' not found in Cloudflare account.")
    zone_id = zones[0]["id"]
    print(f"    Zone ID: {zone_id}")

    # 2. Reconcile Zone Settings
    current_ssl = api_request(token, f"/zones/{zone_id}/settings/ssl")[
        "result"
    ]["value"]
    current_https = api_request(
        token, f"/zones/{zone_id}/settings/always_use_https"
    )["result"]["value"]
    current_min_tls = api_request(
        token, f"/zones/{zone_id}/settings/min_tls_version"
    )["result"]["value"]

    target_settings = spec.get("settings", {})
    if target_settings.get("ssl") and current_ssl != target_settings["ssl"]:
        print(f"  [~] SSL mode: {current_ssl} -> {target_settings['ssl']}")
        if not args.dry_run:
            api_request(
                token,
                f"/zones/{zone_id}/settings/ssl",
                method="PATCH",
                data={"value": target_settings["ssl"]},
            )

    if (
        target_settings.get("always_use_https")
        and current_https != target_settings["always_use_https"]
    ):
        print(
            "  [~] Always Use HTTPS:"
            f" {current_https} -> {target_settings['always_use_https']}"
        )
        if not args.dry_run:
            api_request(
                token,
                f"/zones/{zone_id}/settings/always_use_https",
                method="PATCH",
                data={"value": target_settings["always_use_https"]},
            )

    if (
        target_settings.get("min_tls_version")
        and current_min_tls != target_settings["min_tls_version"]
    ):
        print(
            "  [~] Min TLS version:"
            f" {current_min_tls} -> {target_settings['min_tls_version']}"
        )
        if not args.dry_run:
            api_request(
                token,
                f"/zones/{zone_id}/settings/min_tls_version",
                method="PATCH",
                data={"value": target_settings["min_tls_version"]},
            )

    # 3. Fetch Existing DNS Records
    existing_records = api_request(
        token, f"/zones/{zone_id}/dns_records?per_page=100"
    )["result"]
    existing_by_key = {}
    for r in existing_records:
        existing_by_key[(r["name"], r["type"])] = r

    # 4. Reconcile Desired Records
    created = 0
    updated = 0
    unchanged = 0
    desired_keys = set()

    for rec in spec.get("records", []):
        rec_name = rec["name"]
        if rec_name == "@":
            fqdn = domain
        elif not rec_name.endswith(domain):
            fqdn = f"{rec_name}.{domain}"
        else:
            fqdn = rec_name

        key = (fqdn, rec["type"])
        desired_keys.add(key)
        existing = existing_by_key.get(key)

        payload = {
            "type": rec["type"],
            "name": fqdn,
            "content": rec["content"],
            "ttl": rec.get("ttl", 1),
            "proxied": rec.get("proxied", False),
            "comment": rec.get("comment", "Managed by VYRX GitOps"),
        }

        if not existing:
            print(
                f"  [+] Create {rec['type']} {fqdn} -> {rec['content']} (proxied:"
                f" {rec['proxied']})"
            )
            if not args.dry_run:
                api_request(
                    token,
                    f"/zones/{zone_id}/dns_records",
                    method="POST",
                    data=payload,
                )
            created += 1
        else:
            needs_update = (
                existing["content"] != payload["content"]
                or existing.get("proxied") != payload["proxied"]
                or existing.get("ttl") != payload["ttl"]
            )
            if needs_update:
                print(
                    f"  [~] Update {rec['type']} {fqdn} -> {payload['content']}"
                    f" (proxied: {payload['proxied']})"
                )
                if not args.dry_run:
                    api_request(
                        token,
                        f"/zones/{zone_id}/dns_records/{existing['id']}",
                        method="PUT",
                        data=payload,
                    )
                updated += 1
            else:
                unchanged += 1

    # 5. Prune stale records (opt-in, ownership-scoped). A record is deleted only if all
    # three conditions hold: it is absent from the desired set, it lies inside the zone this
    # run manages, and it carries a comment from this engine's own vocabulary. Everything
    # else - ACME DNS-01 records, manual entries, other tooling - is left alone.
    owned_prefixes = (
        "Zone apex -> ",
        "Wildcard ingress -> ",
        "Node management ",
        "Service ",
        "Managed by VYRX GitOps",
    )
    stale = [
        r
        for (name, type_), r in existing_by_key.items()
        if (name, type_) not in desired_keys
        and (name == domain or name.endswith("." + domain))
        and str(r.get("comment") or "").startswith(owned_prefixes)
    ]
    pruned = 0
    for r in stale:
        if args.prune:
            print(f"  [-] Delete {r['type']} {r['name']} (stale; {r.get('comment')!r})")
            if not args.dry_run:
                api_request(
                    token,
                    f"/zones/{zone_id}/dns_records/{r['id']}",
                    method="DELETE",
                )
            pruned += 1
        else:
            print(
                f"  [ ] Stale {r['type']} {r['name']} ({r.get('comment')!r})"
                " -- re-run with --prune to delete"
            )

    print(
        f"==> DNS Sync Complete: {created} created, {updated} updated,"
        f" {unchanged} unchanged, {len(stale)} stale, {pruned} deleted."
    )


if __name__ == "__main__":
    main()
