{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.my.features.services.klipper;
in
{
  options.my.features.services.klipper = {
    enable = lib.mkEnableOption "Klipper 3D Printing Stack";
  };

  config = lib.mkIf cfg.enable {

    # 1. Klipper Service
    services.klipper = {
      enable = true;
      user = "klipper";
      group = "klipper";
      # Declarative Core & Macros from Git, dynamic calibration state from /var/lib/klipper (docs/architecture.md §6.1)
      configFile = pkgs.writeText "klipper-master.cfg" ''
        # Immutable macros from the Nix store
        [include ${./printer-config/macros.cfg}]

        # Minimal base fallback to allow startup before hardware attach
        [mcu]
        serial: /dev/null

        [printer]
        kinematics: none
        max_velocity: 1000
        max_accel: 1000

        # Dynamic runtime variables / calibration state (Bed-Mesh, Z-Offset, PID)
        # [include /var/lib/klipper/runtime_variables.cfg]
      '';
    };

    # Explicitly define user and group to avoid assertion errors and manage permissions
    users.groups.klipper = { };
    users.users.klipper = {
      isSystemUser = true;
      group = "klipper";
      extraGroups = [ "dialout" ];
    };

    # 2. Moonraker Service
    services.moonraker = {
      enable = true;
      user = "klipper";
      group = "klipper";
      address = "0.0.0.0";
      port = 7125;
      allowSystemControl = true;

      settings = {
        authorization = {
          force_logins = false;
          cors_domains = lib.mkMerge [
            [
              "http://localhost"
              "http://127.0.0.1"
              "https://app.fluidd.xyz"
              "http://app.fluidd.xyz"
              "https://my.mainsail.xyz"
              "http://my.mainsail.xyz"
            ]
            (lib.mkIf (config.my.contracts.provides.klipper.endpoints.mainsail.canonicalDomain != null) [
              "https://${config.my.contracts.provides.klipper.endpoints.mainsail.canonicalDomain}"
            ])
          ];
          trusted_clients = [
            "10.0.0.0/8"
            "127.0.0.0/8"
            "192.168.0.0/16"
            "100.0.0.0/8"
          ];
        };
        file_manager = {
          enable_object_processing = true;
        };
        octoprint_compat = { };
        history = { };

        # Include the secure config generated by sops template for the HA token
        "include ${config.sops.templates."moonraker_power.conf".path}" = { };

        "webcam bed" =
          lib.mkIf (config.my.contracts.provides.klipper.endpoints.cam.canonicalDomain != null)
            {
              location = "printer";
              stream_url = "https://${config.my.contracts.provides.klipper.endpoints.cam.canonicalDomain}/?action=stream";
              snapshot_url = "https://${config.my.contracts.provides.klipper.endpoints.cam.canonicalDomain}/?action=snapshot";
              flip_vertical = true;
            };
      };
    };

    # Bridge Klipper and Moonraker directories
    # This makes Moonraker look into /var/lib/klipper for configs
    systemd.tmpfiles.rules = [
      "L+ /var/lib/moonraker/config - - - - /var/lib/klipper"
    ];

    # Open firewall port for Moonraker (for slicers and direct LAN access)

    # Secrets Management for Moonraker
    sops.secrets."services/home/moonraker_hass_token" = {
      owner = "klipper";
      group = "klipper";
    };

    sops.templates."moonraker_power.conf" = {
      owner = "klipper";
      group = "klipper";
      content = ''
        [power homeassistant_switch]
        type: homeassistant
        protocol: http
        address: 127.0.0.1
        port: 8123
        device: switch.sonoff_basic_ender_sonoff_basic_relay
        token: ${config.sops.placeholder."services/home/moonraker_hass_token"}
        domain: switch
        on_when_job_queued: True
        locked_while_printing: True
        restart_klipper_when_powered: True
      '';
    };

    # 3. Webcam Service (mjpg-streamer)
    services.mjpg-streamer = {
      enable = true;
      inputPlugin = "input_uvc.so -d /dev/video0 -r 1280x720 -f 30";
      # Output to 8081 to avoid conflict with SABnzbd (8080)
      outputPlugin = "output_http.so -p 8081 -w ${pkgs.mjpg-streamer}/share/mjpg-streamer/www";
    };

    # 4. Service Contracts for Caddy, Firewall, and Monitoring
    my.contracts.provides.klipper = {
      endpoints = {
        mainsail = {
          port = 7125;
          protocol = "tcp";
          scope = "internal";
          auth = "authentik";
          accessGroups = [ "family" ];
          subdomain = "mainsail";
          directAccess = {
            enable = true;
            protocol = "tcp";
            interface = "all";
          };
          customExtraConfig = ''
            root * ${pkgs.mainsail}/share/mainsail

            route {
              @api {
                path /websocket /printer/* /api/* /access/* /machine/* /server/*
              }
              reverse_proxy @api 127.0.0.1:7125

              import authentik

              file_server
              try_files {path} /index.html
            }
          '';
          dashboard = {
            description = {
              de = "3D-Drucker-Steuerung und Druckvorschau.";
              en = "3D printer control and print preview.";
            };
            show = true;
            displayName = "Mainsail";
            category = "3D Printing";
            icon = "printer";
          };
        };

        moonraker = {
          port = 7125;
          protocol = "tcp";
          scope = "internal";
          auth = "authentik";
          accessGroups = [ "family" ];
          subdomain = "moonraker";
          directAccess = {
            enable = true;
            protocol = "tcp";
            interface = "all";
          };
          dashboard = {
            show = false;
            displayName = "Moonraker";
            category = "3D Printing";
            icon = "printer";
          };
        };

        cam = {
          port = 8081;
          protocol = "tcp";
          scope = "internal";
          auth = "none";
          subdomain = "cam.moonraker";
          dashboard = {
            show = false;
            displayName = "Klipper Webcam";
            category = "3D Printing";
            icon = "camera";
          };
        };
      };
      storage = {
        stateDirs = [
          "/var/lib/klipper"
          "/var/lib/moonraker"
        ];
      };
    };
  };
}
