{ config, lib, pkgs, ... }:
let
  cfg = config.my.features.services.klipper;
  baseDomain = config.my.features.services.caddy.baseDomain;
in
{
  options.my.features.services.klipper = {
    enable = lib.mkEnableOption "Klipper 3D Printing Stack";
    expose = {
      enable = lib.mkEnableOption "Expose Mainsail and Moonraker via Caddy";
      subdomain = lib.mkOption {
        type = lib.types.str;
        default = "mainsail";
        description = "Subdomain for the Mainsail web interface";
      };
      auth = lib.mkEnableOption "Protect Mainsail with Authentik (Forward Auth)";
    };
  };

  config = lib.mkIf cfg.enable {
    
    # 1. Klipper Service
    services.klipper = {
      enable = true;
      user = "klipper";
      group = "klipper";
      mutableConfig = true; 
      # Initial minimal config to allow Klipper to start
      configFile = pkgs.writeText "klipper-init.cfg" ''
        [mcu]
        serial: /dev/null
        [printer]
        kinematics: none
        max_velocity: 1000
        max_accel: 1000
      '';
    };

    # Explicitly define user and group to avoid assertion errors and manage permissions
    users.groups.klipper = {};
    users.users.klipper = {
      isSystemUser = true;
      group = "klipper";
      extraGroups = [ "dialout" ];
    };

    # 2. Moonraker Service
    services.moonraker = {
      enable = true;
      user = "klipper";
      group = "klipper";
      address = "0.0.0.0";
      port = 7125;
      allowSystemControl = true;
      configDir = "/var/lib/klipper";
      
      settings = {
        authorization = {
          force_logins = false;
          cors_domains = [
            "*.${baseDomain}"
            "https://${cfg.expose.subdomain}.${baseDomain}"
            "http://localhost"
            "http://127.0.0.1"
            "https://app.fluidd.xyz"
            "http://app.fluidd.xyz"
            "https://my.mainsail.xyz"
            "http://my.mainsail.xyz"
          ];
          trusted_clients = [
            "10.0.0.0/8"
            "127.0.0.0/8"
            "192.168.0.0/16"
            "100.0.0.0/8"
          ];
        };
        file_manager = {
            enable_object_processing = true;
        };
        octoprint_compat = {};
        history = {};

        # Include the secure config generated by sops template for the HA token
        "include ${config.sops.templates."moonraker_power.conf".path}" = {};

        "webcam bed" = {
          location = "printer";
          stream_url = "https://cam.moonraker.${baseDomain}/?action=stream";
          snapshot_url = "https://cam.moonraker.${baseDomain}/?action=snapshot";
          flip_vertical = true;
        };
      };
    };

    # Open firewall port for Moonraker (for slicers and direct LAN access)
    networking.firewall.allowedTCPPorts = [ 7125 ];

    # Secrets Management for Moonraker
    sops.secrets.moonraker_hass_token = {
      sopsFile = ../../../secrets/secrets.yaml;
      owner = "klipper";
      group = "klipper";
    };

    sops.templates."moonraker_power.conf" = {
      owner = "klipper";
      group = "klipper";
      content = ''
        [power homeassistant_switch]
        type: homeassistant
        protocol: https
        address: hass.${baseDomain}
        port: 443
        device: switch.sonoff_basic_ender_sonoff_basic_relay
        token: ${config.sops.placeholder.moonraker_hass_token}
        domain: switch
        on_when_job_queued: True
        locked_while_printing: True
        restart_klipper_when_powered: True
      '';
    };

    # 3. Webcam Service (mjpg-streamer)
    services.mjpg-streamer = {
      enable = true;
      inputPlugin = "input_uvc.so -d /dev/video0 -r 1280x720 -f 30";
      # Output to 8081 to avoid conflict with SABnzbd (8080)
      outputPlugin = "output_http.so -p 8081 -w ${pkgs.mjpg-streamer}/share/mjpg-streamer/www";
    };

    # 4. Caddy Exposure - Separate Domains Strategy
    services.caddy.virtualHosts = lib.mkIf cfg.expose.enable {
      # Mainsail Web Interface
      "${cfg.expose.subdomain}.${baseDomain}" = {
        extraConfig = ''
          root * ${pkgs.mainsail}/share/mainsail
          file_server
          try_files {path} /index.html
          ${lib.optionalString cfg.expose.auth "import authentik"}
        '';
      };

      # Dedicated Moonraker API Endpoint
      "moonraker.${baseDomain}" = {
        extraConfig = ''
          reverse_proxy 127.0.0.1:7125
          ${lib.optionalString cfg.expose.auth "import authentik"}
        '';
      };

      # Webcam Stream
      "cam.moonraker.${baseDomain}" = {
        extraConfig = ''
          reverse_proxy 127.0.0.1:8081
        '';
      };
    };
  };
}