{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.my.features.services.klipper;
  ep = config.my.endpoints;
  baseDomain = config.my.features.services.caddy.baseDomain;
in
{
  options.my.features.services.klipper = {
    enable = lib.mkEnableOption "Klipper 3D Printing Stack";
  };

  config = lib.mkIf cfg.enable {

    # 1. Klipper Service
    services.klipper = {
      enable = true;
      user = "klipper";
      group = "klipper";
      mutableConfig = true;
      # Initial minimal config to allow Klipper to start
      configFile = pkgs.writeText "klipper-init.cfg" ''
        [mcu]
        serial: /dev/null
        [printer]
        kinematics: none
        max_velocity: 1000
        max_accel: 1000
      '';
    };

    # Explicitly define user and group to avoid assertion errors and manage permissions
    users.groups.klipper = { };
    users.users.klipper = {
      isSystemUser = true;
      group = "klipper";
      extraGroups = [ "dialout" ];
    };

    # 2. Moonraker Service
    services.moonraker = {
      enable = true;
      user = "klipper";
      group = "klipper";
      address = "0.0.0.0";
      port = 7125;
      allowSystemControl = true;

      settings = {
        authorization = {
          force_logins = false;
          cors_domains = lib.mkMerge [
            [ "*.${baseDomain}" "http://localhost" "http://127.0.0.1" "https://app.fluidd.xyz" "http://app.fluidd.xyz" "https://my.mainsail.xyz" "http://my.mainsail.xyz" ]
            (lib.mkIf (ep.mainsail.subdomain != null) [ "https://${ep.mainsail.subdomain}.${baseDomain}" ])
          ];
          trusted_clients = [
            "10.0.0.0/8"
            "127.0.0.0/8"
            "192.168.0.0/16"
            "100.0.0.0/8"
          ];
        };
        file_manager = {
          enable_object_processing = true;
        };
        octoprint_compat = { };
        history = { };

        # Include the secure config generated by sops template for the HA token
        "include ${config.sops.templates."moonraker_power.conf".path}" = { };

        "webcam bed" = lib.mkIf (ep.mainsail-cam.subdomain != null) {
          location = "printer";
          stream_url = "https://${ep.mainsail-cam.subdomain}.${baseDomain}/?action=stream";
          snapshot_url = "https://${ep.mainsail-cam.subdomain}.${baseDomain}/?action=snapshot";
          flip_vertical = true;
        };
      };
    };

    # Bridge Klipper and Moonraker directories
    # This makes Moonraker look into /var/lib/klipper for configs
    systemd.tmpfiles.rules = [
      "L+ /var/lib/moonraker/config - - - - /var/lib/klipper"
    ];

    # Open firewall port for Moonraker (for slicers and direct LAN access)
    networking.firewall.allowedTCPPorts = [ 7125 ];

    # Secrets Management for Moonraker
    sops.secrets.moonraker_hass_token = {
      sopsFile = ../../../secrets/secrets.yaml;
      owner = "klipper";
      group = "klipper";
    };

    sops.templates."moonraker_power.conf" = {
      owner = "klipper";
      group = "klipper";
      content = ''
        [power homeassistant_switch]
        type: homeassistant
        protocol: http
        address: 127.0.0.1
        port: 8123
        device: switch.sonoff_basic_ender_sonoff_basic_relay
        token: ${config.sops.placeholder.moonraker_hass_token}
        domain: switch
        on_when_job_queued: True
        locked_while_printing: True
        restart_klipper_when_powered: True
      '';
    };

    # 3. Webcam Service (mjpg-streamer)
    services.mjpg-streamer = {
      enable = true;
      inputPlugin = "input_uvc.so -d /dev/video0 -r 1280x720 -f 30";
      # Output to 8081 to avoid conflict with SABnzbd (8080)
      outputPlugin = "output_http.so -p 8081 -w ${pkgs.mjpg-streamer}/share/mjpg-streamer/www";
    };

    # 4. Caddy Exposure - Separate Domains Strategy
    services.caddy.virtualHosts = lib.mkMerge [
      (lib.mkIf (ep.mainsail.subdomain != null) {
        "${ep.mainsail.subdomain}.${baseDomain}" = {
          extraConfig = ''
            root * ${pkgs.mainsail}/share/mainsail

            route {
              @api {
                path /websocket /printer/* /api/* /access/* /machine/* /server/*
              }
              reverse_proxy @api 127.0.0.1:7125

              ${lib.optionalString ep.mainsail.auth "import authentik"}

              file_server
              try_files {path} /index.html
            }
          '';
        };
      })
      (lib.mkIf (ep.moonraker.subdomain != null) {
        "${ep.moonraker.subdomain}.${baseDomain}" = {
          extraConfig = ''
            reverse_proxy 127.0.0.1:7125
            ${lib.optionalString ep.moonraker.auth "import authentik"}
          '';
        };
      })
      (lib.mkIf (ep.mainsail-cam.subdomain != null) {
        "${ep.mainsail-cam.subdomain}.${baseDomain}" = {
          extraConfig = ''
            reverse_proxy 127.0.0.1:8081
          '';
        };
      })
    ];
    # 5. Registry entries for monitoring (Caddy is managed directly above)
    my.endpoints.mainsail = {
      host = config.networking.hostName;
      port = 7125;
      caddy.enable = false;
    };

    my.endpoints.moonraker = {
      host = config.networking.hostName;
      port = 7125;
      caddy.enable = false;
    };

    my.endpoints.mainsail-cam = {
      host = config.networking.hostName;
      port = 8081;
      caddy.enable = false;
    };
  };
}
