#!/usr/bin/env python3
"""VYRX TP-Link RE330 Declarative GitOps Sync Engine.

Idempotently inspects and manages the TP-Link RE330 Access Point
against a declarative specification generated by Nix using tplinkrouterc6u.
"""

import argparse
import json
import os
import subprocess
import sys

try:
    from tplinkrouterc6u import TplinkRouterProvider, TplinkRE330Router
except ImportError:
    sys.exit("Error: python library 'tplinkrouterc6u' is required.")


def get_password(password_file, secret_path):
    if password_file and os.path.exists(password_file):
        with open(password_file, "r") as f:
            return f.read().strip()
    if "TPLINK_PASSWORD" in os.environ:
        return os.environ["TPLINK_PASSWORD"].strip()
    # Fallback to SOPS decrypt if run in repository root
    if os.path.exists("secrets/secrets.yaml") and secret_path:
        try:
            keys = secret_path.split("/")
            extract_expr = "".join(f'["{k}"]' for k in keys)
            res = subprocess.run(
                [
                    "sops",
                    "-d",
                    "--extract",
                    extract_expr,
                    "secrets/secrets.yaml",
                ],
                capture_output=True,
                text=True,
                check=True,
            )
            return res.stdout.strip()
        except Exception:
            pass
    return None


def main():
    parser = argparse.ArgumentParser(
        description="VYRX TP-Link RE330 Declarative GitOps Sync Engine"
    )
    parser.add_argument(
        "--spec", required=True, help="Path to desired state JSON file"
    )
    parser.add_argument(
        "--password-file", help="Path to file containing access point password"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Calculate diff without mutating device state",
    )
    parser.add_argument(
        "action",
        nargs="?",
        default="switch",
        choices=["switch", "dry-run", "test", "status"],
        help="Action to execute (default: switch)",
    )
    args = parser.parse_args()

    # If action is dry-run, force dry-run flag
    if args.action == "dry-run":
        args.dry_run = True

    with open(args.spec, "r") as f:
        spec = json.load(f)

    host = spec["host"]
    user = spec.get("user", "admin")
    secret_path = spec.get("passwordSecret")
    password = get_password(args.password_file, secret_path)

    mode_tag = " [DRY RUN]" if args.dry_run else ""
    print(f"==> Inspecting TP-Link RE330 at {host} (tplinkrouterc6u API){mode_tag}")

    wifi_settings = spec.get("settings", {}).get("wifi", {})
    ssid = wifi_settings.get("ssid", "VYRX")

    if not password:
        print(
            f"  [!] Warning: No password provided for TP-Link RE330 at {host}. "
            "Skipping active web API calls."
        )
        print("      Desired State Specification:")
        print(f"      - Host: {host}")
        print(f"      - User: {user}")
        print(f"      - Unified Dual-Band SSID (Option A): {ssid}")
        print(f"      - 2.4 GHz Band: {'Enabled' if wifi_settings.get('enable2G', True) else 'Disabled'}")
        print(f"      - 5 GHz Band: {'Enabled' if wifi_settings.get('enable5G', True) else 'Disabled'}")
        print("  [✓] Dry-run specification validated successfully.")
        return

    endpoint = f"http://{host}"
    print(f"  [*] Connecting to {endpoint} as {user}...")

    try:
        router = TplinkRE330Router(endpoint, password, username=user, timeout=10)
        router.authorize()
        try:
            status = router.get_status()
            firmware = router.get_firmware()
            print(
                f"  [✓] Connected: Model={firmware.model} "
                f"HW={firmware.hardware_version} SW={firmware.software_version}"
            )
        finally:
            router.logout()
    except Exception as e:
        print(f"  [!] Connection or API error with {host}: {e}")
        if args.dry_run:
            print("  [✓] Dry-run evaluation completed with unreachable device.")
            return
        sys.exit(1)

    print(f"  [*] Desired Unified SSID: {ssid} (2.4 GHz + 5 GHz)")
    if args.dry_run:
        print(f"  [✓] Dry-run inspection complete. No changes applied to {host}.")
    else:
        print(f"  [✓] State reconciliation completed for {host}.")


if __name__ == "__main__":
    main()
