name: Flake Update

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set date
        run: echo "DATE_TODAY=$(date +%Y-%m-%d)" >> "$GITHUB_ENV"

      - name: Update flake.lock
        run: nix flake update

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          title: "chore: update flake.lock"
          branch: "flake-update/${{ env.DATE_TODAY }}"
          delete-branch: true
          body: |
            Automatic `nix flake update`.

            Please verify `nix flake check` result before merging if auto-merge is disabled.

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash
